services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7713368844:AAEzY1dPYSSoeGeec3KeOJzXSxal4H8zUAY
      - key: DATABASE_URL
        value: sqlite:///hafiz.db
      - key: ADMIN_IDS
        value: "1921911753,7149602547"
    pythonVersion: 3.11
